[package]
name = "thejournal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_egui = "0.16.1"
swash = "0.1.4"
serde = "1.0.145"
egui = "0.19.0"
rmp-serde = "1.1.0"
bevy_render = "0.8.1"

[features]
default = ["dynamic"]
dynamic = ["bevy/dynamic"]

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
